config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :tasks

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "tasks#index"
  resources :tasks
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/jwt_token.rb
module JwtToken
  extend ActiveSupport::Concern

  def generate_jwt
    JWT.encode({
                 id: id,
                 exp: 60.days.from_now.to_i,
               }, Rails.application.secrets.secret_key_base)
  end
end

app/models/task.rb
class Task < ApplicationRecord
  # Direct associations

  belongs_to :user

  # Indirect associations

  # Validations

  # Scopes

  def to_s
    body
  end
end

app/models/user.rb
class User < ApplicationRecord
  include JwtToken
  # Direct associations

  has_many   :tasks,
             dependent: :destroy

  # Indirect associations

  # Validations

  # Scopes

  def to_s
    email
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/api/v1/graphiti_controller.rb
class Api::V1::GraphitiController < ApplicationController
  skip_before_action :authenticate_user!

  include Graphiti::Rails::Responders
end

app/controllers/api/v1/tasks_controller.rb
class Api::V1::TasksController < Api::V1::GraphitiController
  def index
    tasks = TaskResource.all(params)
    respond_with(tasks)
  end

  def show
    task = TaskResource.find(params)
    respond_with(task)
  end

  def create
    task = TaskResource.build(params)

    if task.save
      render jsonapi: task, status: :created
    else
      render jsonapi_errors: task
    end
  end

  def update
    task = TaskResource.find(params)

    if task.update_attributes
      render jsonapi: task
    else
      render jsonapi_errors: task
    end
  end

  def destroy
    task = TaskResource.find(params)

    if task.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: task
    end
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::GraphitiController
  def index
    users = UserResource.all(params)
    respond_with(users)
  end

  def show
    user = UserResource.find(params)
    respond_with(user)
  end

  def create
    user = UserResource.build(params)

    if user.save
      render jsonapi: user, status: :created
    else
      render jsonapi_errors: user
    end
  end

  def update
    user = UserResource.find(params)

    if user.update_attributes
      render jsonapi: user
    else
      render jsonapi_errors: user
    end
  end

  def destroy
    user = UserResource.find(params)

    if user.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: user
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  respond_to :html, :json
  before_action :authenticate_user!
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :current_user_must_be_task_user,
                only: %i[edit update destroy]

  before_action :set_task, only: %i[show edit update destroy]

  def index
    @q = Task.ransack(params[:q])
    @tasks = @q.result(distinct: true).includes(:user).page(params[:page]).per(10)
  end

  def show; end

  def new
    @task = Task.new
  end

  def edit; end

  def create
    @task = Task.new(task_params)

    if @task.save
      message = "Task was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @task, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @task.update(task_params)
      redirect_to @task, notice: "Task was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    message = "Task was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to tasks_url, notice: message
    end
  end

  private

  def current_user_must_be_task_user
    set_task
    unless current_user == @task.user
      redirect_back fallback_location: root_path,
                    alert: "You are not authorized for that."
    end
  end

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:user_id, :body, :complete)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  def index
    @users = User.page(params[:page]).per(10)
  end

  def show
    @task = Task.new
  end

  def new
    @user = User.new
  end

  def edit; end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: "User was successfully created."
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: "User was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: "User was successfully destroyed."
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.fetch(:user, {})
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def collapse_search_form
    if params[:q].blank?
      "collapse"
    else
      ""
    end
  end

  def link_to_show_or_back(
    object,
        show_content = "Show",
        back_content = "Back",
        options = {}
  )
    if request.path == url_for(object)
      link_to back_content, :back, options
    else
      link_to show_content, object, options
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    Rtm
  </title>

  <%= render "shared/bootstrapcdn_assets" %>

  <%= csrf_meta_tags %>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/css/tempusdominus-bootstrap-4.min.css" />
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/js/tempusdominus-bootstrap-4.min.js"></script>
  <script src="//maps.google.com/maps/api/js?v=3.24&key=AIzaSyCOTPWiuvyyo6sKoIBzKA4-1ol-vTOIOlM"></script>
  <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>


  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta charset="utf-8">
  <style>
    body { padding-bottom: 70px }
  </style>
</head>

<body>
  <%= render "shared/navbar" %>

  <div class="container">
    <%= render "shared/flashes" %>

    <%= yield %>
  </div>

</body>
</html>

app/views/shared/_bootstrapcdn_assets.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
<link rel="stylesheet"href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" >

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

app/views/shared/_flashes.html.erb
<div class="row">
  <div class="col-md-12">
    <% if notice.present? %>
      <div class="alert alert-success alert-dismissable" role="alert">
        <%= notice %>

        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>

    <% if alert.present? %>
      <div class="alert alert-warning alert-dismissable" role="alert">
        <%= alert %>

        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
  <div class="container">
    <a class="navbar-brand" href="/">
      Rtm
    </a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsible-nav-links" aria-controls="collapsible-nav-links" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="collapsible-nav-links">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Resources
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a href="/tasks" class="dropdown-item">
              Tasks
            </a>
            <a href="/users" class="dropdown-item">
              Users
            </a>
          </div>
        </li>
      </ul>
      <ul class="navbar-nav">
        <% if current_user.blank? %>
          <li class="nav-item">
            <a href="/users/sign_in" class="nav-link">
              Sign in
            </a>
          </li>

          <li class="nav-item">
            <a href="/users/sign_up" class="nav-link">
              Sign up
            </a>
          </li>
        <% else %>
          <li class="nav-item">
            <a href="/users/edit" class="nav-link">
              Edit profile
            </a>
          </li>

          <li class="nav-item">
            <a href="/users/sign_out" data-method="delete" class="nav-link">
              Sign out
            </a>
          </li>
        <% end %>
      </ul>
</nav>

app/views/tasks/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Task #<%= task.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>User</dt>
      <dd>
        <% if @task.user.present? %>
          <%= link_to task.user, task.user %>
        <% end %>
      </dd>

      <dt>Body</dt>
      <dd><%= task.body %></dd>

      <dt>Complete</dt>
      <dd><%= task.complete %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back task, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <% if current_user == @task.user %>
          <%= link_to edit_task_url(task), class: "btn btn-block btn-sm btn-outline-secondary" do %>
            <i class="fas fa-edit"></i>
          <% end %>
        <% end %>
      </div>

      <div class="col">
        <% if current_user == @task.user %>
          <%= link_to task, method: :delete, data: { confirm: "Do you really want to delete this task?" }, class: "btn btn-block btn-outline-secondary" do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(task.updated_at) %> ago
  </div>
</div>

app/views/tasks/_form.html.erb
<% was_validated = task.errors.any? %>

<%= form_with(model: task, local: true, novalidate: true, class: "mb-3") do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <div class="form-group">
    <% body_class = "form-control" %>
    <% body_was_invalid = task.errors.include?(:body) %>

    <% if was_validated %>
      <% if body_was_invalid %>
        <% body_class << " is-invalid" %>
      <% else %>
        <% body_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :body %>
    <%= f.text_field :body, class: body_class, placeholder: "Enter body" %>
    <% if body_was_invalid %>
      <% task.errors.full_messages_for(:body).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-check">
    <% complete_class = "form-check-input" %>
    <% complete_was_invalid = task.errors.include?(:complete) %>

    <% if was_validated %>
      <% if complete_was_invalid %>
        <% complete_class << " is-invalid" %>
      <% else %>
        <% complete_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :complete, class: "form-check-label" do %>
      <%= f.check_box :complete, class: complete_class %> Complete
    <% end %>
    <% if complete_was_invalid %>
      <% task.errors.full_messages_for(:complete).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/tasks/_list_item.html.erb
<%= link_to task, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= task %>
    <small class="text-muted">
      <%= time_ago_in_words(task.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/tasks/_tasks_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "tasks_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :body_cont, "Body contains" %>
    <%= f.text_field :body_cont, :class => "form-control", :placeholder => "Body contains" %>
  </div>

  <div class="form-group">
    <%= f.label :complete_eq, "Complete" %>
    <div>
      <label class="radio-inline">
        <%= f.radio_button :complete_eq, "1", checked: ((params[:q] && params[:q][:complete_eq]) == "1" ? "checked" : "") %> Yes
      </label>
      <label class="radio-inline">
        <%= f.radio_button :complete_eq, "0", checked: ((params[:q] && params[:q][:complete_eq]) == "0" ? "checked" : "")%> No
      </label>
      <label class="radio-inline">
        <%= f.radio_button :complete_eq, ""%> Either
      </label>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :user_email_cont, "User email contains" %>
    <%= f.text_field :user_email_cont, :class => "form-control", :placeholder => "User email contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/tasks" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#tasks_filters">
  Show filters
</a>

app/views/tasks/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Task #<%= @task.id %>
      </h2>

      <div class="card-body">
        <%= render "form", task: @task %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Tasks

      <%= link_to new_task_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "tasks/tasks_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Tasks

        <%= link_to new_task_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @tasks, partial: "list_item", as: :task %>
      </div>
    </div>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Task
      </h2>

      <div class="card-body">
        <%= render "form", task: @task %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @task, partial: "card", as: :task %>
  </div>
</div>

app/views/users/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    User #<%= user.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back user, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_user_url(user), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to user, method: :delete, data: { confirm: "Do you really want to delete this user?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(user.updated_at) %> ago
  </div>
</div>

app/views/users/_form.html.erb
<% was_validated = user.errors.any? %>

<%= form_with(model: user, local: true, novalidate: true, class: "mb-3") do |f| %>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/users/_list_item.html.erb
<%= link_to user, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= user %>
    <small class="text-muted">
      <%= time_ago_in_words(user.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/users/_user_tasks.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Tasks

    <a data-toggle="collapse" href="#user_tasks_new_form">
      Add task
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @user.tasks.each do |task| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to task, task %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="user_tasks_new_form">
        <%= render partial: "users/user_tasks_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/users/_user_tasks_new_form.html.erb
<%= form_with(model: @task, local: true) do |f| %>

  <%= f.hidden_field :user_id, value: @user.id %>

  <div class="form-group">
    <%= f.label :body %>

    <%= f.text_field :body, class: "form-control" %>
  </div>

  <div class="form-check">
    <%= f.check_box :complete, class: "form-check-input" %>
    <%= f.label :complete, class: "form-check-label" %>
  </div>

  <%= f.submit "Create task", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/users/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit User #<%= @user.id %>
      </h2>

      <div class="card-body">
        <%= render "form", user: @user %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Users

      <%= link_to new_user_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>






<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Users

        <%= link_to new_user_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @users, partial: "list_item", as: :user %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New User
      </h2>

      <div class="card-body">
        <%= render "form", user: @user %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @user, partial: "card", as: :user %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "users/user_tasks" %>
  </div>
</div>